steps:
- uses: actions/checkout@v3
- uses: actions/setup-python@v4
- name: Publish a Python distribution to PyPI
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    password: ${{ secrets.PYPI_API_TOKEN }}
  if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')